OnlineShop2022/Areas/Admin/Controllers/RolesManagerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace OnlineShop2022.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RolesManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesManagerController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();

            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteRole(string id)
        {
            if (id != null)
            {
                var role = await _roleManager.FindByIdAsync(id);
                await _roleManager.DeleteAsync(role);
            }

            return RedirectToAction("Index");
        }
    }
}

OnlineShop2022/Areas/Admin/Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop2022.Areas.Admin.Models;
using OnlineShop2022.Models;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnlineShop2022.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserRolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<UserModel> _userManager;    
        public UserRolesController(RoleManager<IdentityRole> roleManager, UserManager<UserModel> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var VMlist = new List<UserRolesViewModel>();

            foreach (var user in users)
            {
                var currentVM = new UserRolesViewModel()
                {
                    User = user,
                    Roles = new List<string>(await _userManager.GetRolesAsync(user))
                };

                VMlist.Add(currentVM);
            }

            return View(VMlist);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return RedirectToAction("Index");
            }

            var roles = await _userManager.GetRolesAsync(user);
            
            await _userManager.RemoveFromRolesAsync(user, roles);

            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Manage(string id)
        {

            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                return RedirectToAction("Index");
            }

            var viewModels = new List<ManageUserRolesViewModel>();

            foreach (var role in _roleManager.Roles)
            {
                var vm = new ManageUserRolesViewModel();
                vm.User = user;
                vm.Role = role;
                vm.IsInRole = await _userManager.IsInRoleAsync(user, role.Name);

                viewModels.Add(vm);
            }

            return View(viewModels);
        }

    }
}

OnlineShop2022/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineShop2022.Data;
using OnlineShop2022.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using OnlineShop2022.Helpers;

namespace OnlineShop2022.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _db;
        private IWebHostEnvironment _webHostEnvironment;
        private Images _images;

        public ProductController(AppDbContext db, IWebHostEnvironment webHostEnvironment, Images images)
        {
            _webHostEnvironment = webHostEnvironment;
            _db = db;
            _images = images;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _db.Products.ToListAsync();
            return View(products);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProductModel product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var file = Request.Form.Files[0];

                    if (file != null)
                    {
                        product.ImagePath = _images.Upload(file, $"/images/products/");
                        await _db.Products.AddAsync(product);
                        await _db.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (Exception)
                {
                    return View(product);
                }
                 
            }
            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, ProductModel product)
        {
            

            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    try
                    {
                        var file = Request.Form.Files[0];

                        if (file != null)
                        {
                            _images.Delete(product.ImagePath);
                            product.ImagePath = _images.Upload(file, $"/images/products/");
                        }
                    }
                    catch(Exception)
                    { }
                   
                    _db.Products.Update(product);
                    await _db.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return NotFound();
                }
            }
            return View(product);
        }

        //GET
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductModel currentProduct = await _db.Products.FindAsync(id);

            if (currentProduct == null)
            {
                return NotFound();
            }

            return View(currentProduct);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id, ProductModel model)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductModel productToDelete = await _db.Products.FindAsync(id);

            if (productToDelete == null)
            {
                return NotFound();
            }

             _db.Products.Remove(productToDelete);
            await _db.SaveChangesAsync();

            _images.Delete(productToDelete.ImagePath);

            return RedirectToAction(nameof(Index));

        }



        //GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductModel currentProduct = await _db.Products.FindAsync(id);

            if (currentProduct == null)
            {
                return NotFound();
            }

            return View(currentProduct);
        }



    }
}

OnlineShop2022/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShop2022</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShop2022</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="RolesManager" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="UserRoles" asp-action="Index">Users</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - OnlineShop</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>